server:
  port: 5000
eureka:
  instance:
    hostname: localhost
#是否向服务注册中心注册自己,默认为true
  client:
    register-with-eureka: false
  #是否检索服务
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/